### ISSUE TITLE
[BUG] The FMHY Safeguard extension pages aren't being marked as FMHY related

### ISSUE THREAD

**Issue by legendaryfishwastaken** [fmhy/FMHY-SafeGuard#14]
### Describe the bug

Whether you open settings or you get an unsafe site popup, the FMHY Safeguard icon is grey, even though it should show the FMHY logo.
![image](https://github.com/user-attachments/assets/c1b1ec67-688f-4f7b-a496-f0b5d56e016e)

### Steps to Reproduce

1. Click the extension icon
2. Click on settings
3. Notice the extension icon shows the "not in wiki" icon

### Expected behavior

It should show the FMHY logo

### FMHY SafeGuard Version

1.1.3

### Before opening this Issue

- [X] I have searched the issues of this repository and believe that this is not a duplicate.

**Comment by ghost** [comment]
@legendaryfishwastaken it's the fmhy-safeguard's extensions page, the dev might make it ignore later

**Comment by kenhendricks00** [comment]
Thanks for catching this! The issue with the FMHY Safeguard icon displaying as grey instead of the extension's logo has been fixed in the latest update. Please update to the latest version when it releases, and you should see the correct icon as expected. Thanks for helping us improve the extension—your feedback is always appreciated!
![image](https://github.com/user-attachments/assets/4ebfb4cd-c5bc-46ef-8d5f-2eb492f464a2)
