### ISSUE TITLE
[BUG] single-page rate limits

### ISSUE THREAD

**Issue by hugo9655** [fmhy/FMHY-SafeGuard#19]
### Describe the bug

Recently the single-page has been reaching rate limits for a lot of people, including showing "worker exceeded resource limits". I (and some others) believe its due to the extension making unneccessary amounts of checks (from all its users).

### Steps to Reproduce

N/A

### Additional information and data

Possible causes:
- the domains are fetched each time the user opens their browser
- the interval of these checks.

A solution would involve removing the check on startup and only fetch new links every 48 hours at the least.

### Before opening this Issue

- [X] I have searched the issues of this repository and believe that this is not a duplicate.

**Comment by kenhendricks00** [comment]
Hey Hugo,
The issue should now be resolved. The extension no longer pulls data on startup, and it checks for updates every 24 hours instead of hourly. These changes should significantly reduce the amount of traffic to the API.
If any issues persist or if there’s anything else you’d like adjusted, just let me know.
Thanks,
Ken

**Comment by hugo9655** [comment]
Awesome, tysm!
